### ISSUE TITLE
Workshop confirmation broken link

### ISSUE THREAD

**Issue by noiserv** [sinfo/ng-sinfo-webapp#140]
On the email sent to confirm a presence on a workshop you send a link to https://sinfo.org/myworkshops, which 404s. Is this the right link or rather https://sinfo.org/workshops

**Comment by fchamicapereira** [comment]
> On the email sent to confirm a presence on a workshop you send a link to https://sinfo.org/myworkshops, which 404s. Is this the right link or rather https://sinfo.org/workshops

We probably forgot to change the anchor. Thanks!

**Comment by fchamicapereira** [comment]
Fixed here: https://github.com/sinfo/cannon-api/commit/cbaa28b195d1bcd4ff6709f5da7d2437e094938e
