### ISSUE TITLE
Major optimizations

### ISSUE THREAD

**Issue by fchamicapereira** [sinfo/ng-sinfo-webapp#178]
Source: https://developers.google.com/web/tools/lighthouse#devtools
Report: [sinfo.org_2019-11-28_16-03-19.report.html.zip](https://github.com/sinfo/ng-sinfo-webapp/files/3921503/sinfo.org_2019-11-28_16-03-19.report.html.zip)

credits to @Stramer1

**Comment by Stramer1** [comment]
More recent one:
[sinfo.org_2020-02-25_12-11-39.report.zip](https://github.com/sinfo/ng-sinfo-webapp/files/4249920/sinfo.org_2020-02-25_12-11-39.report.zip)

**Comment by Stramer1** [comment]
npm i -g lighthouse
lighthouse https://sinfo.org
