### ISSUE TITLE
Change js-gapi to ng-gapi

### ISSUE THREAD

**Issue by Dpac99** [sinfo/ng-sinfo-webapp#281]
Use more appropriate ng-gapi package to handle google auth instead of the more generic js-gapi. Should be used to fix #280

**Comment by bvlourenco** [comment]
``ng-gapi`` uses the soon to be deprecated Google Sign-In JavaScript platform library for Web (will be deprecated at March 31 2023).
Using the official Google library (Google Identity Services): https://developers.google.com/identity/gsi/web/reference/js-reference
