### ISSUE TITLE
Email field on scanner view prompts capitalized text on mobile

### ISSUE THREAD

**Issue by diogotcorreia** [sinfo/ng-sinfo-webapp#283]
Reported by an OpenSoft's member

When typing the email in the field below, mobile keyboards want to insert capitalized text even though it's an email

https://github.com/sinfo/ng-sinfo-webapp/blob/master/src/app/user/link/link.component.html#L100

**Comment by Dpac99** [comment]
Thank you for the feedback. We can fix this, but keep in mind that emails are case insensitive, so it should not make a difference
