### ISSUE TITLE
Use a default image for team members with no image on SINFO landing page

### ISSUE THREAD

**Issue by anees-asghar** [sinfo/ng-sinfo-webapp#452]

**Comment by nalves599** [comment]
@anees-asghar Which image do you recommend?

**Comment by nalves599** [comment]
Used this image:
![hacky-black](https://github.com/user-attachments/assets/9cccc889-b8c2-4124-a9bd-4c491fde6c1b)

**Comment by anees-asghar** [comment]
Sorry just seeing this. Looks great!!
