### ISSUE TITLE
Can't resolve 'ngx-qrcode2'

### ISSUE THREAD

**Issue by carlosfaria94** [sinfo/ng-sinfo-webapp#55]
We have a problem related to `ngx-qrcode2` when running `npm run-script build` for production.

Logs: https://app.netlify.com/sites/sinfo-25/deploys/5a89cc90a6188f492a175411

Running `npm run-script build` reproduces the errors.

**Comment by fchamicapereira** [comment]
you can solve this by installing ngx-qrcode2 (god knows why, because we use qrcode3)
`npm i --save ngx-qrcode2`
